import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/httpskapedcapital">Httpskapedcapital</Link>
        </li>
        <li>
          <Link to="/httpskapedcapitalinv">Httpskapedcapitalinv</Link>
        </li>
        <li>
          <Link to="/httpskapedcapitalborrow">Httpskapedcapitalborrow</Link>
        </li>
        <li>
          <Link to="/httpskapedcapitalloans">Httpskapedcapitalloans</Link>
        </li>
        <li>
          <Link to="/httpskapedcapitalabout">Httpskapedcapitalabout</Link>
        </li>
        <li>
          <Link to="/httpskapedcapitallistings">Httpskapedcapitallistings</Link>
        </li>
        <li>
          <Link to="/httpskapedcapitaldas">Httpskapedcapitaldas</Link>
        </li>
        <li>
          <Link to="/httpskapedcapitalver">Httpskapedcapitalver</Link>
        </li>
        <li>
          <Link to="/httpskapedcapitalsignup">Httpskapedcapitalsignup</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
